#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="${ELF_REAL_WORLD_EXPLICIT_QRELS_REPORT_DIR:-${ROOT_DIR}/tmp/real-world-memory/explicit-qrels}"
SOURCE_FIXTURE_DIR="${ELF_REAL_WORLD_EXPLICIT_QRELS_FIXTURES:-${ROOT_DIR}/apps/elf-eval/fixtures/real_world_memory}"
QREL_FIXTURE_DIR="${ELF_REAL_WORLD_EXPLICIT_QRELS_OUT_FIXTURES:-${REPORT_DIR}/fixtures}"

cd "${ROOT_DIR}"

python3 scripts/materialize-explicit-qrels.py \
	--fixtures "${SOURCE_FIXTURE_DIR}" \
	--out-fixtures "${QREL_FIXTURE_DIR}" \
	--summary-out "${REPORT_DIR}/materialization-summary.json" \
	--ranked-candidates-source oracle \
	--profile generated_public \
	--exclude-without-positive-qrels

cargo run -p elf-eval --bin real_world_job_benchmark -- \
	run \
	--fixtures "${QREL_FIXTURE_DIR}" \
	--out "${REPORT_DIR}/report.json" \
	--run-id real-world-memory-explicit-qrels \
	--adapter-id fixture_explicit_qrels \
	--adapter-name "Explicit qrel oracle fixture pack" \
	--adapter-behavior explicit_qrel_oracle_fixture \
	--adapter-storage-status pass \
	--adapter-runtime-status pass \
	--adapter-notes "Generated by scripts/materialize-explicit-qrels.py from checked-in evidence_links and required_evidence; unmentioned corpus evidence remains unjudged; oracle ranked candidates test metric mechanics only."

cargo run -p elf-eval --bin real_world_job_benchmark -- \
	publish \
	--report "${REPORT_DIR}/report.json" \
	--out "${REPORT_DIR}/report.md"

echo "Explicit qrel benchmark report:"
echo "  ${REPORT_DIR}/materialization-summary.json"
echo "  ${REPORT_DIR}/report.json"
echo "  ${REPORT_DIR}/report.md"
