use crate::search::{
	ChunkCandidate, Config, DiversityDecision, DynamicGateSummary, ExpansionMode, HashMap,
	OffsetDateTime, PayloadLevel, QueryPlanBudget, QueryPlanFusionPolicy, QueryPlanRerankPolicy,
	QueryPlanRetrievalStage, QueryPlanRewrite, RankingRequestOverride, RawSearchPath,
	RecursiveRetrievalResult, ResolvedBlendPolicy, ResolvedDiversityPolicy,
	ResolvedRetrievalSourcesPolicy, ScoredChunk, SearchExplainRelationContext, SearchFilter,
	SearchFilterImpact, TraceCandidateRecord, Uuid, Value,
};

pub(in crate::search) struct FinishSearchArgs<'a> {
	pub(in crate::search) path: RawSearchPath,
	pub(in crate::search) trace_id: Uuid,
	pub(in crate::search) query: &'a str,
	pub(in crate::search) tenant_id: &'a str,
	pub(in crate::search) project_id: &'a str,
	pub(in crate::search) agent_id: &'a str,
	pub(in crate::search) token_id: Option<&'a str>,
	pub(in crate::search) read_profile: &'a str,
	pub(in crate::search) allowed_scopes: &'a [String],
	pub(in crate::search) expanded_queries: Vec<String>,
	pub(in crate::search) expansion_mode: ExpansionMode,
	pub(in crate::search) candidates: Vec<ChunkCandidate>,
	pub(in crate::search) structured_matches: HashMap<Uuid, Vec<String>>,
	pub(in crate::search) recursive_retrieval: Option<RecursiveRetrievalResult>,
	pub(in crate::search) top_k: u32,
	pub(in crate::search) record_hits_enabled: bool,
	pub(in crate::search) ranking_override: Option<RankingRequestOverride>,
	pub(in crate::search) filter: Option<&'a SearchFilter>,
	pub(in crate::search) requested_candidate_k: u32,
	pub(in crate::search) effective_candidate_k: u32,
	pub(in crate::search) payload_level: PayloadLevel,
}

pub(in crate::search) struct FinishSearchPolicies {
	pub(in crate::search) blend_policy: ResolvedBlendPolicy,
	pub(in crate::search) diversity_policy: ResolvedDiversityPolicy,
	pub(in crate::search) retrieval_sources_policy: ResolvedRetrievalSourcesPolicy,
	pub(in crate::search) policy_snapshot: Value,
	pub(in crate::search) policy_id: String,
}

pub(in crate::search) struct FinishSearchScoringResult {
	pub(in crate::search) query_tokens: Vec<String>,
	pub(in crate::search) filtered_candidates: Vec<ChunkCandidate>,
	pub(in crate::search) scored_count: usize,
	pub(in crate::search) snippet_count: usize,
	pub(in crate::search) filtered_candidate_count: usize,
	pub(in crate::search) filter_impact: Option<SearchFilterImpact>,
	pub(in crate::search) trace_candidates: Vec<TraceCandidateRecord>,
	pub(in crate::search) fused_results: Vec<ScoredChunk>,
	pub(in crate::search) selected_results: Vec<ScoredChunk>,
	pub(in crate::search) diversity_decisions: HashMap<Uuid, DiversityDecision>,
	pub(in crate::search) selected_count: usize,
}

pub(in crate::search) struct BuildTraceArgs<'a> {
	pub(in crate::search) path: RawSearchPath,
	pub(in crate::search) trace_id: Uuid,
	pub(in crate::search) query: &'a str,
	pub(in crate::search) tenant_id: &'a str,
	pub(in crate::search) project_id: &'a str,
	pub(in crate::search) agent_id: &'a str,
	pub(in crate::search) token_id: Option<&'a str>,
	pub(in crate::search) read_profile: &'a str,
	pub(in crate::search) expansion_mode: ExpansionMode,
	pub(in crate::search) expanded_queries: Vec<String>,
	pub(in crate::search) allowed_scopes: &'a [String],
	pub(in crate::search) candidate_count: usize,
	pub(in crate::search) filtered_candidate_count: usize,
	pub(in crate::search) snippet_count: usize,
	pub(in crate::search) scored_count: usize,
	pub(in crate::search) fused_count: usize,
	pub(in crate::search) selected_count: usize,
	pub(in crate::search) top_k: u32,
	pub(in crate::search) query_tokens: &'a [String],
	pub(in crate::search) structured_matches: &'a HashMap<Uuid, Vec<String>>,
	pub(in crate::search) recursive_retrieval: Option<&'a RecursiveRetrievalResult>,
	pub(in crate::search) policies: &'a FinishSearchPolicies,
	pub(in crate::search) diversity_decisions: &'a HashMap<Uuid, DiversityDecision>,
	pub(in crate::search) recall_candidates: Vec<ChunkCandidate>,
	pub(in crate::search) fused_results: Vec<ScoredChunk>,
	pub(in crate::search) selected_results: Vec<ScoredChunk>,
	pub(in crate::search) relation_contexts: HashMap<Uuid, Vec<SearchExplainRelationContext>>,
	pub(in crate::search) trace_candidates: Vec<TraceCandidateRecord>,
	pub(in crate::search) now: OffsetDateTime,
	pub(in crate::search) ranking_override: &'a Option<RankingRequestOverride>,
	pub(in crate::search) filter_impact: Option<SearchFilterImpact>,
	pub(in crate::search) payload_level: PayloadLevel,
}

pub(in crate::search) struct BuildQueryPlanArgs<'a> {
	pub(in crate::search) path: RawSearchPath,
	pub(in crate::search) query: &'a str,
	pub(in crate::search) tenant_id: &'a str,
	pub(in crate::search) project_id: &'a str,
	pub(in crate::search) agent_id: &'a str,
	pub(in crate::search) read_profile: &'a str,
	pub(in crate::search) allowed_scopes: &'a [String],
	pub(in crate::search) expansion_mode: ExpansionMode,
	pub(in crate::search) expanded_queries: Vec<String>,
	pub(in crate::search) top_k: u32,
	pub(in crate::search) candidate_k: u32,
	pub(in crate::search) retrieval_sources_policy: &'a ResolvedRetrievalSourcesPolicy,
	pub(in crate::search) recursive_enabled: bool,
	pub(in crate::search) policies: &'a FinishSearchPolicies,
	pub(in crate::search) dynamic_gate: DynamicGateSummary,
}

pub(in crate::search) struct RawSearchExecutionContext {
	pub(in crate::search) tenant_id: String,
	pub(in crate::search) project_id: String,
	pub(in crate::search) agent_id: String,
	pub(in crate::search) token_id: Option<String>,
	pub(in crate::search) top_k: u32,
	pub(in crate::search) candidate_k: u32,
	pub(in crate::search) requested_candidate_k: u32,
	pub(in crate::search) effective_candidate_k: u32,
	pub(in crate::search) query: String,
	pub(in crate::search) read_profile: String,
	pub(in crate::search) payload_level: PayloadLevel,
	pub(in crate::search) filter: Option<SearchFilter>,
	pub(in crate::search) record_hits_enabled: bool,
	pub(in crate::search) ranking_override: Option<RankingRequestOverride>,
	pub(in crate::search) retrieval_sources_policy: ResolvedRetrievalSourcesPolicy,
	pub(in crate::search) expansion_mode: ExpansionMode,
	pub(in crate::search) trace_id: Uuid,
	pub(in crate::search) project_context_description: Option<String>,
	pub(in crate::search) allowed_scopes: Vec<String>,
	pub(in crate::search) policies: FinishSearchPolicies,
}

pub(in crate::search) struct QueryPlanStagesArgs<'a> {
	pub(in crate::search) path: RawSearchPath,
	pub(in crate::search) query: &'a str,
	pub(in crate::search) read_profile: &'a str,
	pub(in crate::search) allowed_scope_count: usize,
	pub(in crate::search) rewrite: &'a QueryPlanRewrite,
	pub(in crate::search) retrieval_stages: &'a [QueryPlanRetrievalStage],
	pub(in crate::search) fusion_policy: &'a QueryPlanFusionPolicy,
	pub(in crate::search) rerank_policy: &'a QueryPlanRerankPolicy,
	pub(in crate::search) budget: &'a QueryPlanBudget,
}

pub(in crate::search) struct BuildSearchItemArgs<'a> {
	pub(in crate::search) cfg: &'a Config,
	pub(in crate::search) policy_id: &'a str,
	pub(in crate::search) blend_policy: &'a ResolvedBlendPolicy,
	pub(in crate::search) diversity_policy: &'a ResolvedDiversityPolicy,
	pub(in crate::search) diversity_decisions: &'a HashMap<Uuid, DiversityDecision>,
	pub(in crate::search) query_tokens: &'a [String],
	pub(in crate::search) structured_matches: &'a HashMap<Uuid, Vec<String>>,
	pub(in crate::search) relation_contexts: &'a HashMap<Uuid, Vec<SearchExplainRelationContext>>,
	pub(in crate::search) scored_chunk: ScoredChunk,
	pub(in crate::search) rank: u32,
}
