# Rust workspace tasks: Clean.

[tasks.clean-baseline-live-docker]
workspace = false
command = "docker"
args = [
	"compose",
	"-f",
	"docker-compose.baseline.yml",
	"down",
	"-v",
	"--remove-orphans",
]

[tasks.clean-parity-docker]
workspace = false
command = "docker"
args = [
	"compose",
	"-f",
	"docker-compose.parity.yml",
	"down",
	"-v",
	"--remove-orphans",
]
