# Rust workspace tasks: Clean.

# Clean
# | task                       | type    | cwd |
# | -------------------------- | ------- | --- |
# | clean-baseline-live-docker | command |     |
# | clean-parity-docker        | command |     |

[tasks.clean-baseline-live-docker]
workspace = false
command = "docker"
args = [
	"compose",
	"-f",
	"docker-compose.baseline.yml",
	"down",
	"-v",
	"--remove-orphans",
]

[tasks.clean-parity-docker]
workspace = false
command = "docker"
args = [
	"compose",
	"-f",
	"docker-compose.parity.yml",
	"down",
	"-v",
	"--remove-orphans",
]

# Format
# | task           | type      | cwd |
# | -------------- | --------- | --- |
# | fmt            | composite |     |
# | fmt-check      | composite |     |
# | fmt-rust       | command   |     |
# | fmt-rust-check | extend    |     |
# | fmt-toml       | command   |     |
# | fmt-toml-check | extend    |     |
