# Rust workspace tasks: Format.

[tasks.fmt]
workspace = false
dependencies = [
	"fmt-rust",
	"fmt-toml",
]

[tasks.fmt-check]
workspace = false
dependencies = [
	"fmt-rust-check",
	"fmt-toml-check",
]

[tasks.fmt-rust]
workspace = false
script = "cargo +nightly fmt --all"

[tasks.fmt-rust-check]
extend = "fmt-rust"
script = "cargo +nightly fmt --all -- --check"

[tasks.fmt-toml]
workspace = false
command = "taplo"
args = [
	"fmt",
]

[tasks.fmt-toml-check]
extend = "fmt-toml"
args = [
	"fmt",
	"--check",
]
