# Rust workspace tasks: Format.

# Format
# | task           | type      | cwd |
# | -------------- | --------- | --- |
# | fmt            | composite |     |
# | fmt-check      | composite |     |
# | fmt-rust       | command   |     |
# | fmt-rust-check | extend    |     |
# | fmt-toml       | command   |     |
# | fmt-toml-check | extend    |     |

[tasks.fmt]
workspace = false
dependencies = [
	"fmt-rust",
	"fmt-toml",
]

[tasks.fmt-check]
workspace = false
dependencies = [
	"fmt-rust-check",
	"fmt-toml-check",
]

[tasks.fmt-rust]
workspace = false
script = "cargo +nightly fmt --all"

[tasks.fmt-rust-check]
extend = "fmt-rust"
script = "cargo +nightly fmt --all -- --check"

[tasks.fmt-toml]
workspace = false
command = "taplo"
args = [
	"fmt",
]

[tasks.fmt-toml-check]
extend = "fmt-toml"
args = [
	"fmt",
	"--check",
]

# Lint
# | task        | type      | cwd |
# | ----------- | --------- | --- |
# | lint        | composite |     |
# | lint-rust   | command   |     |
# | lint-vstyle | command   |     |
