# Rust workspace tasks: Lint Fix.

[tasks.lint-fix]
workspace = false
dependencies = [
	"lint-fix-rust",
	"lint-fix-vstyle",
]

[tasks.lint-fix-rust]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--fix",
	"--allow-dirty",
	"--all-features",
	"--all-targets",
	"--workspace",
	"--",
	"-D",
	"clippy::all",
	"-D",
	"clippy::too_many_lines",
	"-D",
	"clippy::unwrap_used",
	"-D",
	"clippy::use_self",
	"-D",
	"clippy::wildcard_imports",
	"-D",
	"missing-docs",
	"-D",
	"unused-crate-dependencies",
	"-D",
	"warnings",
]

[tasks.lint-fix-vstyle]
workspace = false
command = "cargo"
args = [
	"vstyle",
	"tune",
	"--language",
	"rust",
	"--workspace",
	"--all-features",
	"--strict",
]
