# Rust workspace tasks: Test.

[tasks.test]
clear = true
workspace = false
dependencies = [
	"test-rust",
]

[tasks.test-e2e]
workspace = false
command = "bash"
args = [
	"scripts/context-misranking-harness.sh",
]

[tasks.test-rust]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.test-rust-all]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
	"--run-ignored",
	"all",
]

[tasks.test-rust-integration]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
	"--run-ignored",
	"only",
]
