\ir 00_extensions.sql
\ir tables/001_memory_notes.sql
\ir tables/016_graph_entities.sql
\ir tables/017_graph_entity_aliases.sql
\ir tables/020_graph_predicates.sql
\ir tables/021_graph_predicate_aliases.sql
\ir tables/018_graph_facts.sql
\ir tables/019_graph_fact_evidence.sql
\ir tables/022_graph_fact_supersessions.sql
\ir tables/013_memory_note_fields.sql
\ir tables/009_memory_note_chunks.sql
\ir tables/010_note_chunk_embeddings.sql
\ir tables/014_note_field_embeddings.sql
\ir tables/002_note_embeddings.sql
\ir tables/003_memory_note_versions.sql
\ir tables/023_memory_ingest_decisions.sql
\ir tables/004_memory_hits.sql
\ir tables/005_indexing_outbox.sql
\ir tables/006_search_traces.sql
\ir tables/012_search_trace_candidates.sql
\ir tables/015_search_trace_stages.sql
\ir tables/007_search_trace_outbox.sql
\ir tables/008_llm_cache.sql
\ir tables/011_search_sessions.sql
